services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
        composer install &&
        vendor/bin/phpunit &&
        php bin/basket.php
      "